// src/data.ts
import { JobRequest } from './types';

// Mock data for the spreadsheet
export const jobRequests: JobRequest[] = [
  {
    id: 1,
    request: 'Launch social media campaign for pro...',
    submitted: '15-11-2024',
    submitter: 'Aisha Patel',
    status: 'In-process',
    assignedTo: 'Sophie Choudhury',
    url: 'www.aishapatel...',
    priority: 'Medium',
    dueDate: '20-11-2024',
    estValue: 6200000,
  },
  {
    id: 2,
    request: 'Update press kit for company redesign',
    submitted: '28-10-2024',
    submitter: 'Irfan Khan',
    status: 'Need to start',
    assignedTo: 'Tejas Pandey',
    url: 'www.irfankhanp...',
    priority: 'High',
    dueDate: '30-10-2024',
    estValue: 3500000,
  },
  {
    id: 3,
    request: 'Finalize user testing feedback for app...',
    submitted: '05-12-2024',
    submitter: 'Mark Johnson',
    status: 'In-process',
    assignedTo: 'Rachel Lee',
    url: 'www.markjohns...',
    priority: 'Medium',
    dueDate: '10-12-2024',
    estValue: 4750000,
  },
  {
    id: 4,
    request: 'Design new features for the website',
    submitted: '10-01-2025',
    submitter: 'Emily Green',
    status: 'Complete',
    assignedTo: 'Tom Wright',
    url: 'www.emilygreen...',
    priority: 'Low',
    dueDate: '15-01-2025',
    estValue: 5900000,
  },
  {
    id: 5,
    request: 'Prepare financial report for Q4',
    submitted: '25-01-2025',
    submitter: 'Jessica Brown',
    status: 'Blocked',
    assignedTo: 'Kevin Smith',
    url: 'www.jessicabro...',
    priority: 'Low',
    dueDate: '30-01-2025',
    estValue: 2800000,
  },
  // Add more dummy data to fill the spreadsheet if needed
  {
    id: 6,
    request: 'Review Q1 marketing strategy',
    submitted: '01-02-2025',
    submitter: 'Sarah Connor',
    status: 'Need to start',
    assignedTo: 'John Doe',
    url: 'www.sarahc.com',
    priority: 'High',
    dueDate: '10-02-2025',
    estValue: 7000000,
  },
  {
    id: 7,
    request: 'Develop new product prototype',
    submitted: '15-02-2025',
    submitter: 'Michael Scott',
    status: 'In-process',
    assignedTo: 'Dwight Schrute',
    url: 'www.michaels.com',
    priority: 'High',
    dueDate: '28-02-2025',
    estValue: 9500000,
  },
  {
    id: 8,
    request: 'Optimize website SEO',
    submitted: '01-03-2025',
    submitter: 'Pam Beesly',
    status: 'Complete',
    assignedTo: 'Jim Halpert',
    url: 'www.pamb.com',
    priority: 'Medium',
    dueDate: '15-03-2025',
    estValue: 4000000,
  },
  {
    id: 9,
    request: 'Customer feedback analysis',
    submitted: '10-03-2025',
    submitter: 'Angela Martin',
    status: 'In-process',
    assignedTo: 'Oscar Martinez',
    url: 'www.angelam.com',
    priority: 'Low',
    dueDate: '20-03-2025',
    estValue: 3000000,
  },
  {
    id: 10,
    request: 'Prepare annual budget report',
    submitted: '20-03-2025',
    submitter: 'Kevin Malone',
    status: 'Need to start',
    assignedTo: 'Stanley Hudson',
    url: 'www.kevinm.com',
    priority: 'High',
    dueDate: '31-03-2025',
    estValue: 5000000,
  },
  {
    id: 11,
    request: 'Onboard new sales team members',
    submitted: '01-04-2025',
    submitter: 'Phyllis Lapin-Vance',
    status: 'In-process',
    assignedTo: 'Bob Vance',
    url: 'www.phyllisv.com',
    priority: 'Medium',
    dueDate: '10-04-2025',
    estValue: 2500000,
  },
  {
    id: 12,
    request: 'Update internal documentation',
    submitted: '05-04-2025',
    submitter: 'Andy Bernard',
    status: 'Complete',
    assignedTo: 'Erin Hannon',
    url: 'www.andyb.com',
    priority: 'Low',
    dueDate: '15-04-2025',
    estValue: 1500000,
  },
  {
    id: 13,
    request: 'Plan company holiday party',
    submitted: '10-04-2025',
    submitter: 'Creed Bratton',
    status: 'Need to start',
    assignedTo: 'Meredith Palmer',
    url: 'www.creedb.com',
    priority: 'Medium',
    dueDate: '25-04-2025',
    estValue: 1000000,
  },
  {
    id: 14,
    request: 'Research new market trends',
    submitted: '15-04-2025',
    submitter: 'Darryl Philbin',
    status: 'In-process',
    assignedTo: 'Toby Flenderson',
    url: 'www.darrylp.com',
    priority: 'High',
    dueDate: '30-04-2025',
    estValue: 8000000,
  },
  {
    id: 15,
    request: 'Develop new training modules',
    submitted: '20-04-2025',
    submitter: 'Gabe Lewis',
    status: 'Blocked',
    assignedTo: 'Nellie Bertram',
    url: 'www.gabel.com',
    priority: 'Low',
    dueDate: '05-05-2025',
    estValue: 3200000,
  },
  {
    id: 16,
    request: 'Redesign company website landing page',
    submitted: '25-04-2025',
    submitter: 'Kelly Kapoor',
    status: 'In-process',
    assignedTo: 'Ryan Howard',
    url: 'www.kellyk.com',
    priority: 'High',
    dueDate: '10-05-2025',
    estValue: 6800000,
  },
  {
    id: 17,
    request: 'Conduct quarterly performance reviews',
    submitted: '01-05-2025',
    submitter: 'Clark Green',
    status: 'Need to start',
    assignedTo: 'Pete Miller',
    url: 'www.clarkg.com',
    priority: 'Medium',
    dueDate: '15-05-2025',
    estValue: 4500000,
  },
  {
    id: 18,
    request: 'Prepare presentation for investors',
    submitted: '05-05-2025',
    submitter: 'Erin Hannon',
    status: 'Complete',
    assignedTo: 'Andy Bernard',
    url: 'www.erinh.com',
    priority: 'High',
    dueDate: '20-05-2025',
    estValue: 10000000,
  },
  {
    id: 19,
    request: 'Organize team building event',
    submitted: '10-05-2025',
    submitter: 'Nellie Bertram',
    status: 'In-process',
    assignedTo: 'Gabe Lewis',
    url: 'www.nellieb.com',
    priority: 'Low',
    dueDate: '25-05-2025',
    estValue: 1800000,
  },
  {
    id: 20,
    request: 'Update CRM system with new leads',
    submitted: '15-05-2025',
    submitter: 'Pete Miller',
    status: 'Need to start',
    assignedTo: 'Clark Green',
    url: 'www.petem.com',
    priority: 'Medium',
    dueDate: '30-05-2025',
    estValue: 5500000,
  },
];

